In [0]:
!pip install Faker

In [0]:
from snowflake.snowpark.session import Session
from snowflake.snowpark import functions as F
from snowflake.snowpark import types as T
from snowflake.snowpark.types import *
from snowflake.snowpark.functions import udf, avg, col,lit,call_udf

User = dbutils.secrets.get("snowparkdetails", "username")
Password = dbutils.secrets.get("snowparkdetails", "password")
Account = dbutils.secrets.get("snowparkdetails", "account")
TenandId = dbutils.secrets.get("gen2-storage", "tenant-id")
SchemaName = "raw"
DatabaseName = "CustDB"
Warehouse = "cluster1"
DBrole = "ACCOUNTADMIN"
CONNECTION_PARAMETERS = {
    'account': Account,
    'user': User,
    'password': Password,
    'schema': SchemaName,
    'database': DatabaseName,
    'warehouse': Warehouse,
    'role':DBrole,
}

session = Session.builder.configs(CONNECTION_PARAMETERS).create()

print(session.sql('select current_warehouse(), current_database(), current_schema()').collect())

In [0]:
from faker import Faker

faker = Faker()

In [0]:
allempData = ((faker.name(), "Sales", 4000), \
    (faker.name(), "Sales", 5000),  \
    (faker.name(), "Sales", faker.random_int(5000, 10000)),   \
    (faker.name(), "Sales", 5000),    \
    (faker.name(), "Sales", faker.random_int(5000, 10000)), \
    (faker.name(), "Finance", 3000),  \
    (faker.name(), "Finance", 4500),  \
    (faker.name(), "Finance", 7500),    \
    (faker.name(), "IT", faker.random_int(5000, 10000)),\
    (faker.name(), "IT", faker.random_int(5000, 10000)),\
    (faker.name(), "Marketing", 5500), \
    (faker.name(), "Marketing", 5500),\
    (faker.name(), "Marketing", faker.random_int(5000, 10000))\
  )
 
columns= ["EmployeeName", "Department", "Salary"]
df = session.createDataFrame(data = allempData, schema = columns)
df.show()

In [0]:
df.schema.fields

In [0]:
# from pyspark.sql.window import Window
# from pyspark.sql.functions import row_number,rank,dense_rank,percent_rank,ntile,lead,lag,col

from snowflake.snowpark import functions as F
from snowflake.snowpark.window import Window
from snowflake.snowpark.functions import row_number,rank,dense_rank,percent_rank,ntile,lead,lag,col,call_builtin,call_udf,avg,min,max,sum,array_agg
from snowflake.snowpark.types import IntegerType,StringType,DoubleType,StructField,StructType,FloatType

windowSpec  = Window.partition_by("Department").orderBy("Salary")
windowSpec_NOB  = Window.partition_by("Department")

df.withColumn("row_number",row_number().over(windowSpec)).toPandas()

,EMPLOYEENAME,DEPARTMENT,SALARY,ROW_NUMBER
0,Nathan Wilkinson,IT,7560,1
1,Jimmy Patterson PhD,IT,9798,2
2,Travis Barker,Marketing,5500,1
3,Devin Ingram,Marketing,5500,2
4,Ashley Jones,Marketing,7382,3
5,Amanda Vargas,Finance,3000,1
6,Melissa Decker DDS,Finance,4500,2
7,Rodney Romero,Finance,7500,3
8,Johnny Johnston,Sales,4000,1
9,Maurice Dean,Sales,5000,2
10,Veronica Davis,Sales,5000,3
11,Devin Nash,Sales,6591,4
12,Chelsea Schmidt,Sales,6647,5

In [0]:
df.withColumn("rank",rank().over(windowSpec)).\
withColumn("dense_rank",dense_rank().over(windowSpec)).filter(col("dense_rank")<=2).show()

In [0]:
df.withColumn("percentage_rank",percent_rank().over(windowSpec))\
.toPandas()

,EMPLOYEENAME,DEPARTMENT,SALARY,PERCENTAGE_RANK
0,Nathan Wilkinson,IT,7560,0.00
1,Jimmy Patterson PhD,IT,9798,1.00
2,Travis Barker,Marketing,5500,0.00
3,Devin Ingram,Marketing,5500,0.00
4,Ashley Jones,Marketing,7382,1.00
5,Amanda Vargas,Finance,3000,0.00
6,Melissa Decker DDS,Finance,4500,0.50
7,Rodney Romero,Finance,7500,1.00
8,Johnny Johnston,Sales,4000,0.00
9,Maurice Dean,Sales,5000,0.25
10,Veronica Davis,Sales,5000,0.25
11,Devin Nash,Sales,6591,0.75
12,Chelsea Schmidt,Sales,6647,1.00

In [0]:
df.withColumn("lag",lag("salary",1).over(windowSpec)).\
   withColumn("lead",lead("salary",1).over(windowSpec)) \
      .show()

In [0]:
df.withColumn("lead",lead("salary",1).over(windowSpec)) \
      .toPandas()

,EMPLOYEENAME,DEPARTMENT,SALARY,LEAD
0,Nathan Wilkinson,IT,7560,9798.0
1,Jimmy Patterson PhD,IT,9798,NaN
2,Travis Barker,Marketing,5500,5500.0
3,Devin Ingram,Marketing,5500,7382.0
4,Ashley Jones,Marketing,7382,NaN
5,Amanda Vargas,Finance,3000,4500.0
6,Melissa Decker DDS,Finance,4500,7500.0
7,Rodney Romero,Finance,7500,NaN
8,Johnny Johnston,Sales,4000,5000.0
9,Maurice Dean,Sales,5000,5000.0
10,Veronica Davis,Sales,5000,6591.0
11,Devin Nash,Sales,6591,6647.0
12,Chelsea Schmidt,Sales,6647,NaN

In [0]:
#Using built-in function in Snowflake - avg 
df.withColumn("AvgSal",call_builtin("avg", col("salary")).over(windowSpec_NOB)).withColumn("SumSal",sum(col("salary")).over(windowSpec_NOB)) \
   .toPandas()

,EMPLOYEENAME,DEPARTMENT,SALARY,AVGSAL,SUMSAL
0,Johnny Johnston,Sales,4000,5447.600,27238
1,Maurice Dean,Sales,5000,5447.600,27238
2,Devin Nash,Sales,6591,5447.600,27238
3,Veronica Davis,Sales,5000,5447.600,27238
4,Chelsea Schmidt,Sales,6647,5447.600,27238
5,Amanda Vargas,Finance,3000,5000.000,15000
6,Melissa Decker DDS,Finance,4500,5000.000,15000
7,Rodney Romero,Finance,7500,5000.000,15000
8,Jimmy Patterson PhD,IT,9798,8679.000,17358
9,Nathan Wilkinson,IT,7560,8679.000,17358
10,Travis Barker,Marketing,5500,6127.333,18382
11,Devin Ingram,Marketing,5500,6127.333,18382
12,Ashley Jones,Marketing,7382,6127.333,18382

In [0]:
#Withour orderby in window function
df.withColumn("AvgSal",avg("salary").over(windowSpec_NOB)).withColumn("SumSal",sum(col("salary")).over(windowSpec_NOB)) \
   .toPandas()

,EMPLOYEENAME,DEPARTMENT,SALARY,AVGSAL,SUMSAL
0,Johnny Johnston,Sales,4000,5447.600,27238
1,Maurice Dean,Sales,5000,5447.600,27238
2,Devin Nash,Sales,6591,5447.600,27238
3,Veronica Davis,Sales,5000,5447.600,27238
4,Chelsea Schmidt,Sales,6647,5447.600,27238
5,Amanda Vargas,Finance,3000,5000.000,15000
6,Melissa Decker DDS,Finance,4500,5000.000,15000
7,Rodney Romero,Finance,7500,5000.000,15000
8,Jimmy Patterson PhD,IT,9798,8679.000,17358
9,Nathan Wilkinson,IT,7560,8679.000,17358
10,Travis Barker,Marketing,5500,6127.333,18382
11,Devin Ingram,Marketing,5500,6127.333,18382
12,Ashley Jones,Marketing,7382,6127.333,18382

In [0]:
#with order by in window function
df.withColumn("AvgSal",avg("salary").over(windowSpec)).withColumn("SumSal",sum("salary").over(windowSpec)) \
    .show(12)

In [0]:

windowSpec_unboundedpre = Window.partitionBy(col("Department")).orderBy("Salary").rowsBetween(Window.unboundedPreceding,Window.currentRow)
windowSpec_prevrow = Window.partitionBy(col("Department")).orderBy("Salary").rowsBetween(-1,Window.currentRow)
windowSpec_nextvrow = Window.partitionBy(col("Department")).orderBy("Salary").rowsBetween(Window.currentRow,1)

In [0]:
#Running totals per department
windowSpec_unboundedpre = Window.partitionBy(col("Department")).orderBy("Salary")\
.rowsBetween(Window.unboundedPreceding,Window.currentRow)

df.withColumn("AvgSal",avg("Salary").over(windowSpec_unboundedpre))\
.withColumn("RunningTotal",sum(col("Salary")).over(windowSpec_unboundedpre)) \
    .show(11)

In [0]:
# Sum with next rows
df.withColumn("SumSal",sum(col("Salary")).over(windowSpec_nextvrow)) \
    .show(11)

In [0]:
#Sum with prev row
df.withColumn("SumSal",sum(col("Salary")).over(windowSpec_prevrow)) \
    .show(11)

In [0]:
 #GroupBy and Agg 
df.groupBy(['Department']).agg([sum('Salary').alias("SumofSalary"), \
                                 avg('Salary').alias("AvgofSalary"), \
                                 max('Salary').alias("MaxofSalary")]).show()

In [0]:


newempData = ((faker.name(), "Sales", faker.random_int(5000, 10000)), \
    (faker.name(), "Sales", faker.random_int(5000, 10000)),  \
    (faker.name(), "Sales", faker.random_int(5000, 10000)),   \
    (faker.name(), "Sales", faker.random_int(5000, 10000)),    \
    (faker.name(), "Sales", faker.random_int(5000, 10000)), \
    (faker.name(), "Finance", faker.random_int(5000, 10000)),  \
    (faker.name(), "Finance", faker.random_int(5000, 10000)),  \
    (faker.name(), "Finance", faker.random_int(5000, 10000)),
    (faker.name(), "IT", faker.random_int(5000, 10000)),\
    (faker.name(), "IT", faker.random_int(5000, 10000)),\
    (faker.name(), "Marketing", faker.random_int(5000, 10000)), \
    (faker.name(), "Marketing", faker.random_int(5000, 10000)),\
    (None, "Marketing", faker.random_int(5000, 10000)),\
    (faker.name(), "Marketing", faker.random_int(5000, 10000))\
  )

empSchema = StructType([ \
    StructField("EmployeeName",StringType(),True), \
    StructField("Department",StringType(),True), \
    StructField("Salary", IntegerType(), True) \
  ])
 

df_udf = session.createDataFrame(data = newempData, schema = empSchema)

In [0]:
df_udf.toPandas()

,EMPLOYEENAME,DEPARTMENT,SALARY
0,Tyler Miller,Sales,6443
1,Alicia Newton MD,Sales,9895
2,Mrs. Denise George,Sales,5535
3,Michael Mack,Sales,7439
4,Brian Davis,Sales,5577
5,Oscar Lowe,Finance,7029
6,Sarah Miller,Finance,9110
7,Patricia Wallace,Finance,7869
8,Jennifer Edwards,IT,8171
9,Heather Gray MD,IT,6537
10,Jean Jackson,Marketing,7752
11,Grant Rodriguez,Marketing,6144
12,None,Marketing,9953
13,Shane Higgins,Marketing,6559

In [0]:
type(df_udf)

In [0]:
df_udf.createOrReplaceTempView("emp")

In [0]:
session.sql("select * from emp").show()

In [0]:
session.sql("list @azure_csv_stage/customer/parquetFiles/").show(max_width=1000)

##### Reading JSON Data

In [0]:
from snowflake.snowpark.functions import sql_expr,json_extract_path_text,parse_json,to_json,get_path

In [0]:
df_json = session.read.json("@azure_csv_stage/jsondata/")
df_json.select(sql_expr("$1[0]:Fuel").alias("Fuel")\
              ,sql_expr("$1[0]:Transmission").alias("Transmission")\
              ,sql_expr("$1[0]:about").alias("about")\
              ,sql_expr("$1[0]:cost").alias("Cost")).show()

##### Reading CSV Files

In [0]:
cust_schema = StructType([
    StructField("C_CUSTKEY", IntegerType()),
    StructField("C_NAME", StringType()),
    StructField("C_ADDRESS", StringType()),
    StructField("C_NATIONKEY", ShortType()),
    StructField("C_PHONE", StringType()),
    StructField("C_ACCTBAL", DoubleType()),
    StructField("C_MKTSEGMENT", StringType()),
    StructField("C_COMMENT", StringType())
])

df_cust= session.read.option("skip_header", 1).option("field_delimiter", ",")\
.option("FIELD_OPTIONALLY_ENCLOSED_BY", '"')\
.schema(cust_schema).csv("@azure_csv_stage/customer/csvFiles/")
df_cust.show(3)

##### Reading and writing to Parquet

In [0]:
#Reading parquet Files
session.read.parquet("@azure_csv_stage/customer/parquetFiles/").select("C_NAME","C_PHONE").show(5)

In [0]:
#Writing to Parquet without any partitions
df_cust.write.copy_into_location('@azure_csv_stage/customer/newsnowparkParquetFiles/', \
 file_format_type="parquet", header=True,OVERWRITE=True)

In [0]:
#Writing to Parquet with partitions
df_cust.write.copy_into_location('@azure_csv_stage/customer/newsnowparkpartitionedParquetFiles/', 
 partition_by="'C_MKTSEGMENT=' || C_MKTSEGMENT || '/C_NATIONKEY=' || to_varchar(C_NATIONKEY)" ,\
 file_format_type="parquet", header=True)

In [0]:

session.sql("list @azure_csv_stage/customer/newsnowparkpartitionedParquetFiles").show(max_width=1000)

##### Writing to Table

In [0]:
df_cust.write.mode("append").saveAsTable("NewCustomers")

In [0]:
session.sql("list @azure_csv_stage/customer/csvFiles/").show(max_width=100)

In [0]:
df_stages=session.sql(" list @azure_csv_stage/sesnsordata/").collect()
for val in df_stages:
    print(val.name)